TestUsers/Models/Brand.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestUsers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.Motorcycles = new HashSet<Motorcycle>();
            this.Categories = new HashSet<Category>();
            this.Dealers = new HashSet<Dealer>();
        }
    
        public int BrandId { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motorcycle> Motorcycles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealer> Dealers { get; set; }
    }
}

TestUsers/Controllers/BrandsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestUsers.Models;

namespace TestUsers.Controllers
{
    public class BrandsController : Controller
    {
        private NavEcommerceDBfirstEntities19 db = new NavEcommerceDBfirstEntities19();

        // GET: Brands
        [Authorize()]
        public async Task<ActionResult> Index()
        {
            return View(await db.Brands.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await db.Brands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brands/Create
        [Authorize()]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "BrandId,Name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: Dealers/Edit/5
        [Authorize()]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var brandViewModel = new BrandVM
            {
                Brand = db.Brands.Include(i => i.Dealers).Include(i => i.Motorcycles).First(i => i.BrandId == id),

            };

            if (brandViewModel.Brand == null)
                return HttpNotFound();

            var allDealersList = db.Dealers.ToList();
            brandViewModel.AllDealers = allDealersList.Select(d => new SelectListItem
            {
                Text = d.Name,
                Value = d.DealerId.ToString()
            });

            var allMotocyclesList = db.Motorcycles.ToList();
            brandViewModel.AllMotorcycles = allMotocyclesList.Select(m => new SelectListItem
            {
                Text = m.Model,
                Value = m.MotorcycleId.ToString()
            });

            var imageData = db.Brands.Where(m => m.Image == brandViewModel.Brand.Image).FirstOrDefault();

            if (imageData != null)
            {
                brandViewModel.Brand.Image = imageData.Image;
            }

            return View(brandViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BrandVM brandViewModel, HttpPostedFileBase image)
        {

            if (brandViewModel == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (ModelState.IsValid)
            {
                var brandToUpdate = db.Brands
                    .Include(i => i.Dealers).Include(i => i.Motorcycles).First(i => i.BrandId == brandViewModel.Brand.BrandId);

                if (TryUpdateModel(brandToUpdate, "Brand", new string[] { "Name", "Image", "BrandId", "Dealers", "Motorcycles" }))
                {
                    var newDealer = db.Dealers.Where(
                       m => brandViewModel.SelectedDealers.Contains(m.DealerId)).ToList();
                    var updatedDealers = new HashSet<int>(brandViewModel.SelectedDealers);
                    foreach (Dealer dealer in db.Dealers)
                    {
                        if (!updatedDealers.Contains(dealer.DealerId))
                        {
                            brandToUpdate.Dealers.Remove(dealer);
                        }
                        else
                        {
                            brandToUpdate.Dealers.Add((dealer));
                        }
                    }

                    var newMotorcycle = db.Motorcycles.Where(
                        m => brandViewModel.SelectedMotorcycles.Contains(m.MotorcycleId)).ToList();
                    var updatedMotorcycles = new HashSet<int>(brandViewModel.SelectedMotorcycles);
                    foreach (Motorcycle motorcycle in db.Motorcycles)
                    {
                        if (!updatedMotorcycles.Contains(motorcycle.MotorcycleId))
                        {
                            brandToUpdate.Motorcycles.Remove(motorcycle);
                        }
                        else
                        {
                            brandToUpdate.Motorcycles.Add((motorcycle));
                        }
                    }

                    if (image != null)
                    {
                        byte[] data;
                        using (Stream inputStream = image.InputStream)
                        {
                            MemoryStream memoryStream = inputStream as MemoryStream;
                            if (memoryStream == null)
                            {
                                memoryStream = new MemoryStream();
                                inputStream.CopyTo(memoryStream);
                            }
                            data = memoryStream.ToArray();
                        }

                        brandToUpdate.Image = data;
                    }

                    db.Entry(brandToUpdate).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }

            var allDealersList = db.Dealers.ToList();
            brandViewModel.AllDealers = allDealersList.Select(d => new SelectListItem
            {
                Text = d.Name,
                Value = d.DealerId.ToString()
            });

            var allMotorcyclesList = db.Motorcycles.ToList();
            brandViewModel.AllMotorcycles = allMotorcyclesList.Select(d => new SelectListItem
            {
                Text = d.Model,
                Value = d.MotorcycleId.ToString()
            });
            return View(brandViewModel);
        }

        // GET: Brands/Delete/5
        [Authorize()]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await db.Brands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Brand brand = await db.Brands.FindAsync(id);
            db.Brands.Remove(brand);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestUsers/Views/Brands/Create.cshtml
@model TestUsers.Models.Brand

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestUsers/Views/Brands/Delete.cshtml
@model TestUsers.Models.Brand

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestUsers/Views/Brands/Details.cshtml
@model TestUsers.Models.Brand

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BrandId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestUsers/Views/Brands/Edit.cshtml
@model TestUsers.Models.BrandVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Brands", FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Brand.BrandId)

        <span>
            <label>Upload Image</label>
            <br />
            <input type="file" name="image" id="image" />
        </span>

        @if (Model.Brand.Image != null)
        {
            <label for="Image">Image </label>
            <br />
            <img src="data:image;base64,@System.Convert.ToBase64String(Model.Brand.Image)" width="80" height="80" />
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Brand.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AllDealers, "Select Dealers", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedDealers, Model.AllDealers)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AllMotorcycles, "Select Motorcycles", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ListBoxFor(m => m.SelectedMotorcycles, Model.AllMotorcycles)
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestUsers/Views/Brands/Index.cshtml
@model IEnumerable <TestUsers.Models.Brand>
>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BrandId }) |
                @Html.ActionLink("Details", "Details", new { id = item.BrandId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.BrandId })
            </td>
        </tr>
    }

</table>